defaults:
  - _paths
  - _self_

resume_from_ckpt: null
sampling_rate: 16000
num_training_steps: 150000
float32_matmul_precision: high
run_id: null  # may be overridden by wandb when using wandblogger
seed: 137  # will be used for torch and numpy

logger:
  _partial_: True
  _target_: pytorch_lightning.loggers.WandbLogger
  project: streamflow
  save_dir: "./runs/"

model:
  _target_: sgmse.model.FlowModel
  sigma_x: 0.001
  sigma_y: 0.35
  lr: 5e-4
  sampling_rate: ${sampling_rate}
  backbone:
    _target_: sgmse.backbones.ncsnpp_orig.NCSNpp
    ch_mult: [1, 2, 2, 2]
    num_res_blocks: 2
    discriminative: False
    conditional: True
    scale_by_sigma: False
    image_size: 320
    input_channels: 4
    spatial_channels: 1
    centered: True
    pad_time_to: 8  # downsampling factor 2^(len(ch_mult) - 1)
  feature_extractor:
    _target_: sgmse.feature_extractors.CompressedAmplitudeComplexSTFT
    n_fft: 640            # 40ms window
    hop_length: 320       # 20ms hop -- aligned with Lyra V2
    cut_highest_freqs: 1  # cut Nyquist on forward, pad back in on invert
    # use sqrt-Hann window for easier OLA procedure in streaming mode
    window: hann
    sqrt_window: True
    # compression args
    alpha: 0.5
    beta: 1.0
    normalized_stft: True
    compression_is_learnable: False
    sampling_rate: ${sampling_rate}
  data_module:
    _target_: sgmse.data_module.AudioDataModule
    batch_size: 12  # per device
    format: paired_dirs
    train_path: ${ewv2_lyra_train_path}
    valid_path: ${ewv2_lyra_valid_path}
    test_path: ${ewv2_lyra_test_path}
    sampling_rate: ${sampling_rate}
    target_duration: 32512  # (128-1) * 16ms*16kHz) for center=True and 128 target frames
    spatial_channels: 1
    num_workers: 8
    pin_memory: True
    # crop paired files to shorter one. this happens sometimes in our BWR task (downsample->upsample is ambiguous)
    crop_paired_to_shorter: True
  optimizer_constructor:
    # this will receive parameters and lr when actually instantiated by the model
    _partial_: True
    _target_: sgmse.soap_optimizer.SOAP
  scheduler_config:
    scheduler_constructor:
      _partial_: True
      _target_: sgmse.util.schedulers.get_cosine_schedule_with_warmup
      num_warmup_steps: 1000  # warmup for 1000 steps
      num_training_steps: ${num_training_steps}
      num_cycles: 0.5  # cosine decay
    scheduler_config_dict:
      # scheduler_config for lightning
      name: warmup_cosine
      interval: step  # step-wise scheduler
      frequency: 1  # every step
      strict: True  # fail if not found in optimizer

trainer_constructor:
  _partial_: True
  _target_: pytorch_lightning.Trainer
  devices: 2
  accelerator: gpu
  precision: 32
  max_steps: ${num_training_steps}
  log_every_n_steps: 50
  num_sanity_val_steps: 1
  check_val_every_n_epoch: 1
  val_check_interval: 1.0
  strategy:
    _target_: pytorch_lightning.strategies.DDPStrategy
    find_unused_parameters: False
  gradient_clip_val: 5.0
  gradient_clip_algorithm: norm
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      save_last: True
      filename: "{epoch:02d}"
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: valid_loss
      mode: min
      save_top_k: 1
      save_last: True
      filename: "{epoch:02d}-{valid_loss:.4f}"
    - _target_: pytorch_lightning.callbacks.TQDMProgressBar
      refresh_rate: 50
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: step
