defaults:
  - _paths
  - streamfm_se_predgen
  - _self_

# checkpoint of wrapped flow model
ckpt: checkpoints/streamfm_se_predgen.ckpt

solver_model:
  _target_: sgmse.model.CustomRKSolverEnhancementModel
  base_solver: rk4_3over8
  b_min: 0.05  # every gradient should be used with to at least 5% in the weighted sum
  c_max: 0.85  # no evaluated time point should exceed 0.85
  a_penalty: [-4.0, 4.0, 0.1]  # penalize `a` values beyond [-4, 4] with weight 0.1
  lr: 1e-3
  losses:
    - _target_: sgmse.losses.signal.MultiScaleSTFTLoss
      window_lengths: [320, 512, 640]
      n_hops: 4
      mag_weight: 0.0
      log_weight: 1.0
      sampling_rate: ${sampling_rate}
      loss_fn:
        _target_: torch.nn.MSELoss
        reduction: mean
      weight: 0.001
    - _target_: sgmse.losses.signal.PESQLoss
      sampling_rate: ${sampling_rate}
      weight: 0.1
  optimizer_constructor:
    # this will receive parameters and lr when actually instantiated by the model
    _partial_: True
    _target_: torch.optim.Adam
    fused: True  # should be faster
  data_module:
    _target_: sgmse.data_module.AudioDataModule
    batch_size: 5  # per device
    target_duration: 32512  # (128-1) * 16ms*16kHz) for center=True and 128 target frames
    peak_normalize_clean: True
    random_neg_gain_noisy: -12  # dB
    format: ears_wham
    train_path: ${ewv2_train_csv}
    valid_path: ${ewv2_valid_csv}
    test_path: ${ewv2_test_csv}
    sampling_rate: ${sampling_rate}
    spatial_channels: 1
    num_workers: 4
    pin_memory: True


num_training_steps: 25000

trainer_constructor:
  max_steps: ${num_training_steps}
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      save_last: True
      filename: "{step:02d}"
      every_n_train_steps: ${num_training_steps}
    - _target_: pytorch_lightning.callbacks.TQDMProgressBar
      refresh_rate: 50
