defaults:
  - _paths
  - streamfm_derev
  - _self_

model:
  backbone:
    attn_bottleneck: True
    attn_bottleneck_kwargs:
      causal_attn: True
      window_size: 64
      norm_type: subband_grouped_batchnorm
